### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by brianpkennedy** [3jane/numpy_ext#12]
Hi there,

the requirements.txt has dependencies on very specific versions of numpy and job lib

```
numpy==1.20.1
joblib==1.0.1
````

Are these specific versions crucial to the execution code, or can they be relaxed to be more compatible . i.e.

```
numpy>=1.20.1,<1.21
joblib>=1.0.1,<1.1.0
```

I am having issues installing this package into a project of mine that has a different numpy dependency.

Thanks in advance.

**Comment by saninstein** [comment]
@brianpkennedy 
Tests say that everything is okay, so I will add upgraded requirements in the new update.

**Comment by brianpkennedy** [comment]
thank you!
