### ISSUE TITLE
Numpy_Ext not yet supported for Numpy 1.22 (python 3.10)?

### ISSUE THREAD

**Issue by MichaelSoegaard** [3jane/numpy_ext#14]
Platform: Windows 10
Anaconda environment with python 3.10 installed.
Numpy version: 1.22

When I try to install numpy_ext it downgrades Numpy to version 1.20.3 which isn't supported to run under Python 3.10 and then numpy_ext fails.

Part of the error message:

`Collecting numpy_ext
  Using cached numpy_ext-0.9.6-py3-none-any.whl (6.9 kB)
Collecting numpy<1.21,>=1.20.1
  Using cached numpy-1.20.3.zip (7.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting joblib<1.1.0,>=1.0.1
 Using cached joblib-1.0.1-py3-none-any.whl (303 kB)
Building wheels for collected packages: numpy
  Building wheel for numpy (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Michael\Anaconda3\envs\python310\python.exe' 'C:\Users\Michael\Anaconda3\envs\python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\Michael\AppData\Local\Temp\tmpdayu8j06'
       cwd: C:\Users\Michael\AppData\Local\Temp\pip-install-5dirr115\numpy_5153723f3f2b4e6ba2137681641308a2
  Complete output (844 lines):
  setup.py:66: RuntimeWarning: NumPy 1.20.3 may not yet support Python 3.10.
    warnings.warn(
  Running from numpy source directory.`

The complete error message is in the attached txt.
[numpy_ext error.txt](https://github.com/3jane/numpy_ext/files/7958973/numpy_ext.error.txt)

Is it correct that numpy_ext can't run under python 3.10?

**Comment by davidxbuck** [comment]
I came to ask a similar question about compatibility, but it's rater concerning that in half a year, no-one has responded to a simple question about whether this library is going to be kept up-to-date. Has this project died? It looks like a great solution for a particular need, but not if it's not being maintained at all.

**Comment by saninstein** [comment]
@davidxbuck @MichaelSoegaard 
I am sorry for your waiting. Python3.10 should works with v0.9.7
