### ISSUE TITLE
Can more current versions of numpy be used with this package?

### ISSUE THREAD

**Issue by BlackArbsCEO** [3jane/numpy_ext#3]

**Comment by saninstein** [comment]
@BlackArbsCEO 
Yes, all tests are passing successfully on numpy 1.18.3., so it should work. Just install numpy after numpy_ext

https://github.com/3jane/numpy_ext/blob/50c271bf8749bd47a9d60e622a03f7c52d9b9aa2/.github/workflows/pythonpackage.yml#L24
https://github.com/3jane/numpy_ext/actions/runs/91047346

UPD
We upgraeded numpy in newer version of numpy_ext (0.9.2)
